### ISSUE TITLE
[suggest] adding multiple plots feature

### ISSUE THREAD

**Issue by EminYagmahan** [CieNTi/serial_port_plotter#12]
Hello,

Thank you so much for your work. I have the suggestion to be able to assign several input parameters to several plots. This is how I imagine the process:

1. Choose how many plots should be displayed
2. Allocation of one or more labels to one or more plots
3. Possibility to freely modify the Y-axes of the selected plot.

Thank you very much for your efforts.

**Comment by R4ddd** [comment]
Hello,

Thank you so much for your work. 
I would like to add data entry data input to COM Port.

**Comment by R4ddd** [comment]
Hello!
I have already added sending data to the COM port.
https://github.com/R4ddd/serial_port_plotter
