### ISSUE TITLE
can`t build on ubuntu 16.04.2 with message:

### ISSUE THREAD

**Issue by sevkin** [CieNTi/serial_port_plotter#4]
qmake -qt=5
make

> g++ -m64 -Wl,-O1 -o serial_port_plotter main.o mainwindow.o qcustomplot.o helpwindow.o qrc_serial_port_plotter.o qrc_style.o moc_mainwindow.o moc_qcustomplot.o moc_helpwindow.o   -L/usr/X11R6/lib64 serial_port_plotter_res.o -lQt5PrintSupport -lQt5Widgets -lQt5Gui -lQt5SerialPort -lQt5Core -lGL -lpthread 
> **g++: error: serial_port_plotter_res.o: No such file or directory**
> Makefile:160: recipe for target 'serial_port_plotter' failed
> make: *** [serial_port_plotter] Error 1

**Comment by CieNTi** [comment]
Woops sorry for the big delay, i just tested it on Debian and found the same issue. Initially I just tried to compile only on Windows and that was my mistake.

I just commited and I think the latest code will run for you now.

Thanks for the feedback and reopen the issue if you think is not done yet.
