### ISSUE TITLE
Windows release miss for 1.3

### ISSUE THREAD

**Issue by BR38** [CieNTi/serial_port_plotter#6]
Hi, 
I am an happy user of the version 1.2 ( last available exe release). I am not familiar with compilation tools used ( iccs...). Could it possible to write down a short explaination to compile for window? oa a faster way for user ... add an exe release ;-).
Thanks
Bertrand

**Comment by CieNTi** [comment]
Sorry, this release was not made by me and forgot to update the notes.

Here you have it, [updated now](https://github.com/CieNTi/serial_port_plotter/releases/tag/v1.3.0)

**Comment by BR38** [comment]
Thanks!

**Comment by CieNTi** [comment]
I suppose it's solved now, so I close this issue, but feel free to comment here again if related.

Thanks for warn about it :D
